### ISSUE TITLE
Scala Native support

### ISSUE THREAD

**Issue by bphenriques** [circe/circe-yaml#360]
Add support for Scala-Native similarly to https://github.com/circe/circe/issues/1077

I have limited knowledge on how to add support for Scala Native but it is something I am available to explore (following https://github.com/circe/circe/pull/2017 as a starting point). Would that be too tricky?

I am exploring a native application that reads YAML file and this library would come in handy.

**Comment by armanbilge** [comment]
Unfortunately Scala Native support for this project is impossible, because this uses a Java dependency for Yaml.

The good news is that I've now published a fork of this lib that uses Virtus Lab Scala Yaml and is cross-published for Scala Native (and Scala.js).

https://github.com/armanbilge/circe-scala-yaml

See also:
- https://github.com/circe/circe-yaml/issues/285
- https://github.com/circe/circe-yaml/issues/186

**Comment by bphenriques** [comment]
Thank you, I will take a look 👍
